<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>StreamTeamDeck.Plugin</RootNamespace>
    <AssemblyName>StreamTeamDeck.Plugin</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StreamTeamDeck.Core\StreamTeamDeck.Core.csproj" />
  </ItemGroup>

</Project>
